global:
  scrape_interval: 5s  # как часто опрашивать

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rule.yml"

scrape_configs:
  - job_name: 'expenseservice'
    static_configs:
      - targets: ['host.docker.internal:8083']  # если сервис не в Docker
        # или:
        # - targets: ['taskservice:8083']       # если сервис в docker-compose
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']