
services:
  redis:
    image: "eqalpha/keydb:x86_64_v5.3.3"
    container_name: redis
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    volumes:
      - "data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped
  robotssrvs:
    image: robotsrvs
    container_name: robotsrvsapp
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
    - postgres
    - redis
    - rabbitmq
  prometheus:
      image: prom/prometheus:v2.44.0
      container_name: prometheus-archapp-lab4
      ports:
         - "9090:9090"
      volumes:
         - ../internaldata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
         - ../internaldata/prometheus/alert_rule.yml:/etc/prometheus/alert_rule.yml
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15671:15672"
      - "15692:15692" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true"
    volumes:
      - ../internaldata/rabbitmq-data:/var/lib/rabbitmq
      - ../internaldata/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ../internaldata/grafana-data:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ../internaldata/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: robotdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  controlsrvs:
    image: controlsrvs
    container_name: controlapp
    restart: unless-stopped
    ports:
      - "8084:8084"
    depends_on:
    - postgres
    - redis
    - rabbitmq

volumes:
  data:
    driver: local
  pgdata: